version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: projet-devops
      MYSQL_USER: user 
      MYSQL_PASSWORD: user 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: dev
      APP_SECRET: "caf97b573dcb37745a0d8bd717fea441"
      DATABASE_URL: mysql://root:root@db/projet-devops
    volumes:
      - .:/var/www/html/projet-devops/
    ports:
      - "9000:9000"
    # command: sh -c "while ! nc -z db 3306; do sleep 1; done; php bin/console doctrine:migrations:migrate --no-interaction"
    depends_on:
      - db

  web:
    container_name: web
    image: nginx:1.21-alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html/projet-devops
    depends_on:
      - php